language: objective-c
osx_image: xcode8
podfile: Example/Podfile
script:
  - xcodebuild -workspace Example/Polymorph.xcworkspace -scheme Polymorph-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone SE,OS=10.0' build test
  - bash <(curl -s https://codecov.io/bash)
  - pod lib lint
